allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  maplibre-gl: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@internationalized/date@3.12.2'
  - '@nuxt/ui@4.8.1'
